"""empty message

Revision ID: 046c054ee3d5
Revises: 69b763e0c775
Create Date: 2023-02-16 20:20:02.653003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '046c054ee3d5'
down_revision = '69b763e0c775'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('birth_year', sa.String(length=256), nullable=True),
    sa.Column('eye_color', sa.String(length=256), nullable=True),
    sa.Column('gender', sa.String(length=256), nullable=True),
    sa.Column('hair_color', sa.String(length=256), nullable=True),
    sa.Column('height', sa.String(length=256), nullable=True),
    sa.Column('mass', sa.String(length=256), nullable=True),
    sa.Column('skin_color', sa.String(length=256), nullable=True),
    sa.Column('homeworld', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Characters')
    # ### end Alembic commands ###
