"""empty message

Revision ID: 72e0ee143665
Revises: 046c054ee3d5
Create Date: 2023-02-16 20:56:08.821515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72e0ee143665'
down_revision = '046c054ee3d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=256), nullable=True))
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Characters', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('image')

    # ### end Alembic commands ###
